-- tables
-- Table EXERCISE
CREATE TABLE EXERCISE (
    ID int  NOT NULL  AUTO_INCREMENT,
    REPEATS int  NOT NULL,
    DURATION int  NOT NULL,
    EXERCISE_TYPE_ID int  NOT NULL,
    TRAINING_ID int  NOT NULL,
    CONSTRAINT EXERCISE_pk PRIMARY KEY (ID)
);

-- Table EXERCISE_TYPE
CREATE TABLE EXERCISE_TYPE (
    ID int  NOT NULL  AUTO_INCREMENT,
    NAME varchar(40)  NOT NULL,
    DESCRIPTION varchar(255)  NOT NULL,
    USER_ID int  NOT NULL,
    CONSTRAINT EXERCISE_TYPE_pk PRIMARY KEY (ID)
);

-- Table TRAINING
CREATE TABLE TRAINING (
    ID int  NOT NULL  AUTO_INCREMENT,
    DATE_CREATED timestamp  NOT NULL,
    USER_ID int  NOT NULL,
    CONSTRAINT TRAINING_pk PRIMARY KEY (ID)
);

-- Table USER
CREATE TABLE USER (
    ID int  NOT NULL  AUTO_INCREMENT,
    FIRST_NAME varchar(70)  NOT NULL,
    LAST_NAME varchar(70)  NOT NULL,
    EMAIL varchar(70)  NOT NULL,
    PASSWORD varchar(100)  NOT NULL,
    ROLE varchar(20)  NOT NULL,
    ENABLED bool  NOT NULL,
    DATE_CREATED timestamp  NOT NULL,
    CONSTRAINT USER_pk PRIMARY KEY (ID)
);

-- foreign keys
-- Reference:  EXERCISE_EXERCISE_TYPE (table: EXERCISE)

ALTER TABLE EXERCISE ADD CONSTRAINT EXERCISE_EXERCISE_TYPE FOREIGN KEY EXERCISE_EXERCISE_TYPE (EXERCISE_TYPE_ID)
    REFERENCES EXERCISE_TYPE (ID);
-- Reference:  EXERCISE_TRAINING (table: EXERCISE)

ALTER TABLE EXERCISE ADD CONSTRAINT EXERCISE_TRAINING FOREIGN KEY EXERCISE_TRAINING (TRAINING_ID)
    REFERENCES TRAINING (ID);
-- Reference:  EXERCISE_TYPE_User (table: EXERCISE_TYPE)

ALTER TABLE EXERCISE_TYPE ADD CONSTRAINT EXERCISE_TYPE_User FOREIGN KEY EXERCISE_TYPE_User (USER_ID)
    REFERENCES USER (ID);
-- Reference:  TRAINING_USER (table: TRAINING)

ALTER TABLE TRAINING ADD CONSTRAINT TRAINING_USER FOREIGN KEY TRAINING_USER (USER_ID)
    REFERENCES USER (ID);

-- End of file.
